# Copyright © Mandala Consulting, LLC., 2025. All Rights Reserved. Created by Alexander Fields https://www.alexanderfields.me on 2025-06-08 13:27:40
# Edited by Alexander Fields https://www.alexanderfields.me 2025-07-02 11:48:25
name: .NET Test

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Logging Tests
      run: dotnet test MC.Logging.Tests/MandalaConsulting.Logging.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Run Memory Tests
      run: dotnet test MC.Memory.Tests/MandalaConsulting.Memory.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Run APIMiddlewares Tests
      run: dotnet test MC.APIMiddlewares.Tests/MandalaConsulting.APIMiddlewares.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Run Repository.Mongo Tests
      run: dotnet test MC.Repository.Mongo.Tests/MandalaConsulting.Repository.Mongo.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*'
