name: Publish Release NuGet Packages

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'Version increment type'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for version tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Pack all projects
        run: |
          echo "Packing all NuGet packages..."
          dotnet pack MC.Logging/MandalaConsulting.Logging.csproj --configuration Release --no-build --output ./nupkgs
          dotnet pack MC.Memory/MandalaConsulting.Memory.csproj --configuration Release --no-build --output ./nupkgs
          dotnet pack MC.APIMiddlewares/MandalaConsulting.APIMiddlewares.csproj --configuration Release --no-build --output ./nupkgs
          dotnet pack MC.Repository.Mongo/MandalaConsulting.Repository.Mongo.csproj --configuration Release --no-build --output ./nupkgs
          dotnet pack MC.Objects/MandalaConsulting.Objects.csproj --configuration Release --no-build --output ./nupkgs
          dotnet pack MC.Objects.API/MandalaConsulting.Objects.API.csproj --configuration Release --no-build --output ./nupkgs

      - name: Push to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "Publishing packages to NuGet.org..."
          for package in ./nupkgs/*.nupkg; do
            echo "Publishing $package..."
            dotnet nuget push "$package" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
          done

      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./nupkgs/*.nupkg
          retention-days: 7