# Copyright © Mandala Consulting, LLC., 2025. All Rights Reserved. Created by Alexander Fields https://www.alexanderfields.me on 2025-06-08 14:28:17
# Edited by Alexander Fields https://www.alexanderfields.me 2025-07-02 11:48:25
name: Publish NuGet Packages

on:
  workflow_dispatch:  # Allow manual triggering
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Run all tests
      run: dotnet test --no-build --configuration Release --verbosity normal
    
    - name: Pack MandalaConsulting.Logging
      run: dotnet pack MC.Logging/MandalaConsulting.Logging.csproj --configuration Release --no-build --output nupkgs
    
    - name: Pack MandalaConsulting.Memory
      run: dotnet pack MC.Memory/MandalaConsulting.Memory.csproj --configuration Release --no-build --output nupkgs
    
    - name: Pack MandalaConsulting.APIMiddlewares
      run: dotnet pack MC.APIMiddlewares/MandalaConsulting.APIMiddlewares.csproj --configuration Release --no-build --output nupkgs
    
    - name: Pack MandalaConsulting.Repository.Mongo
      run: dotnet pack MC.Repository.Mongo/MandalaConsulting.Repository.Mongo.csproj --configuration Release --no-build --output nupkgs
    
    - name: Pack MandalaConsulting.Objects
      run: dotnet pack MC.Objects/MandalaConsulting.Objects.csproj --configuration Release --no-build --output nupkgs
    
    - name: Pack MandalaConsulting.Objects.API
      run: dotnet pack MC.Objects.API/MandalaConsulting.Objects.API.csproj --configuration Release --no-build --output nupkgs
    
    - name: Push NuGet packages to NuGet.org
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
    - name: Push NuGet packages to GitHub
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/roku674/index.json --skip-duplicate
